package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LibroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAllPropertiesEquals(Libro expected, Libro actual) {
        assertLibroAutoGeneratedPropertiesEquals(expected, actual);
        assertLibroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAllUpdatablePropertiesEquals(Libro expected, Libro actual) {
        assertLibroUpdatableFieldsEquals(expected, actual);
        assertLibroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAutoGeneratedPropertiesEquals(Libro expected, Libro actual) {
        assertThat(expected)
            .as("Verify Libro auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroUpdatableFieldsEquals(Libro expected, Libro actual) {
        assertThat(expected)
            .as("Verify Libro relevant properties")
            .satisfies(e -> assertThat(e.getIsbn()).as("check isbn").isEqualTo(actual.getIsbn()))
            .satisfies(e -> assertThat(e.getPrecio()).as("check precio").isEqualTo(actual.getPrecio()))
            .satisfies(e -> assertThat(e.getNombreAutor()).as("check nombreAutor").isEqualTo(actual.getNombreAutor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroUpdatableRelationshipsEquals(Libro expected, Libro actual) {
        // empty method
    }
}
